[package]
name = "wavrec"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
ctrlc = "3.4.5"
uuid = {version = "1.10.0", features = ["v4", "fast-rng"]}
wasapi = "0.15.0"

[dev-dependencies]
